### ISSUE TITLE
Off hand detection.

### ISSUE THREAD

**Issue by grendel111111** [javierriveracastro/betteroll-swade#492]
Similar to the trademarked weapon there is now a setting to put a weapon in your off hand in the equipment management. Can we get a way to either detect it, or automatically do -2 to the skill unless you have ambidextrous?

**Comment by javierriveracastro** [comment]
Sure, but... could it be another edges that remove that penalty?.

**Comment by grendel111111** [comment]
Yes. I think detection would be best so you can use it with 2 gun kid etc as well.

**Comment by javierriveracastro** [comment]
Done

**Comment by grendel111111** [comment]
It works great but needs an override for ambidextrous so it won't give the off hand penalty.

**Comment by javierriveracastro** [comment]
It should be there. At least it works on my test world.

**Comment by grendel111111** [comment]
![image](https://user-images.githubusercontent.com/80164119/197242624-50029420-2dca-44ab-9922-5a478671d6c7.png)
Gralie is using a sword in her off hand, but has Ambidex and still gets the -2 penalty.
I'm on BR2 3.4 running on The Forge,
Foundry 10.288
SWADE 2.0.6

**Comment by javierriveracastro** [comment]
Done, again, hopefully.
